name: Submit New Workflow
description: Submit a workflow for inclusion in the Gallery
title: "Submit Workflow: [workflow name]"
labels: ["new", "workflow"]
assignees:
  - vitorgalvao
body:
  - type: checkboxes
    attributes:
      label: "Preflight"
      description: Click the `▸` icons to expand details.
      options:
        - label: <details><summary>The Alfred team has invited me to submit this workflow.</summary>Only submit this form if explicitely asked. To be considered for the Alfred Gallery, <a href="https://www.alfredforum.com/forum/3-share-your-workflows/">share your workflow on the Alfred forum</a>.</details>
          required: true
        - label: <details><summary>I have submitted a separate pull request with workflow instructions following the <a href="https://alfred.app/submit/styleguide/">Style Guide</a>.</summary>Submit a pull request adding <code>your-name/workflow-name</code> under the <code><a href="https://github.com/alfredapp/gallery-edits/tree/main/workflows/">/workflows/</a></code> folder. Inside, create a <code>readme.md</code> file for the instructions, an <code>images</code> folder for the screenshots, and an <code>icon.png</code> with the workflow icon at 256x256px. See <a href="https://github.com/alfredapp/gallery-edits/tree/main/workflows/alfredapp/disk-usage/">alfredapp/disk-usage</a> for an example.</details>
          required: true
  - type: checkboxes
    attributes:
      label: "The submitted workflow:"
      description: Click the `▸` icons to expand details.
      options:
        - label: <details><summary>Uses sensible keywords with several characters.</summary>Keywords which are too short can get lost amongst results or conflict with other workflows. While there are exceptions, workflow keywords (including in Script Filters, File Filters, or similar) should in general be at least three characters long. Ideally they will also be <a href="https://www.alfredapp.com/help/workflows/advanced/keywords/#configurable">user-configurable</a>.</details>
          required: true
        - label: <details><summary>Has an icon of at least 256x256 px.</summary>A minimum main icon size of 256x256 px is required to guarantee image quality.</details>
          required: true
        - label: <details><summary>Does not use an auto-updater.</summary>Workflows available in the Gallery are updatable from Alfred. Workflows must never update themselves to not cause conflicts.</details>
          required: true
        - label: <details><summary>Does not download extra software.</summary>Every bit of executable code must be contained in the workflow. The workflow must never install extra software itself, including (but not limited to) running <code>pip install</code>, <code>gem install</code>, <code>brew install</code>, or <code>curl</code>ing a binary. Bundling libraries with the workflow is accepted. <a href="https://brew.sh/">Homebrew</a> dependencies must be <a href="https://www.alfredapp.com/help/kb/dependencies/">handled by Alfred</a>.</details>
          required: true
        - label: <details><summary>Does not contain unsigned and non-notarised binaries.</summary>Workflows must not have unsigned and non-notarised binaries, or otherwise try to bypass this macOS security feature (e.g. by removing quarantine). Scripts don’t fall into this category.</details>
          required: true
  - type: markdown
    attributes:
      value: |
        ## Workflow Details
  - type: input
    attributes:
      label: Homepage
      description: Link to the page where the workflow is hosted. E.g. a GitHub repository.
      placeholder: https://github.com/username/repo/
    validations:
      required: true
  - type: input
    attributes:
      label: Alfred Forum page
      description: Link to the workflow page [on the forum](https://www.alfredforum.com/forum/3-share-your-workflows/).
      placeholder: https://www.alfredforum.com/topic/nnnn-name
    validations:
      required: true
  - type: input
    attributes:
      label: Tags
      description: Short list of tag suggestions to identify the workflow.
      placeholder: markdown, notes, text-manipulation, …
  - type: textarea
    attributes:
      label: Homebrew dependencies
      description: Alfred [can manage homebrew dependencies](https://www.alfredapp.com/help/kb/dependencies/). List them here if your workflow has any, one per line. They must all be from [the main Homebrew tap](https://github.com/Homebrew/homebrew-core).
